######  Attributes Supported by Integration Apps #######
# id: Internal Id for the integrations, used by the hooks
# logo: place the image in /public/dashboard/images/integrations and reference here
# i18n_key: the key under which translations for the integration is placed in en.yml
# action: if integration requires external redirect url
# hook_type: ( account / inbox )
# allow_multiple_hooks: whether multiple hooks can be created for the integration
# settings_json_schema: the json schema used to validate the settings hash (https://json-schema.org/)
# settings_form_schema: the formulate schema used in frontend to render settings form (https://vueformulate.com/)
########################################################
captain:
  id: captain
  logo: captain.png
  i18n_key: captain
  action: /captain
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema: {
    "type": "object",
    "properties": {
        "access_token": { "type": "string" },
        "account_id": { "type": "string" },
        "account_email": { "type": "string" },
        "assistant_id": { "type": "string" },
        "inbox_ids": { "type": "strings" },
      },
    "required": ["access_token", "account_id", "account_email", "assistant_id"],
    "additionalProperties": false,
  }
  settings_form_schema: [
    {
      "label": "Access Token",
      "type": "text",
      "name": "access_token",
      "validation": "required",
    },
    {
      "label": "Account ID",
      "type": "text",
      "name": "account_id",
      "validation": "required",
    },
    {
      "label": "Account Email",
      "type": "text",
      "name": "account_email",
      "validation": "required",
    },
    {
      "label": "Assistant Id",
      "type": "text",
      "name": "assistant_id",
      "validation": "required",
    },
    {
      "label": "Inbox Ids",
      "type": "text",
      "name": "inbox_ids",
      "validation": "",
    },
  ]
  visible_properties: []
webhooks:
  id: webhook
  logo: webhooks.png
  i18n_key: webhooks
  action: /webhook
  hook_type: account
  allow_multiple_hooks: true
openai:
  id: openai
  logo: openai.png
  i18n_key: openai
  action: /openai
  hook_type: account
  allow_multiple_hooks: false
  settings_json_schema: {
    "type": "object",
    "properties": {
        "api_key": { "type": "string" },
        "label_suggestion": { "type": "boolean" },
      },
    "required": ["api_key"],
    "additionalProperties": false,
  }
  settings_form_schema: [
    {
      "label": "API Key",
      "type": "text",
      "name": "api_key",
      "validation": "required",
    },
    {
      "label": "Show label suggestions",
      "type": "checkbox",
      "name": "label_suggestion",
      "validation": "",
    },
  ]
  visible_properties: ['api_key', 'label_suggestion']
